// <auto-generated />
using System;
using ContractManagement.Infrastructure.Persistence.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    partial class ServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContractAggregate", b =>
                {
                    b.Property<string>("AggregateId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("AggregateId");

                    b.ToTable("ContractAggregate");

                    b.HasData(
                        new
                        {
                            AggregateId = "CTR-20220502-9999",
                            Version = 1L
                        });
                });

            modelBuilder.Entity("ContractEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<uint>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ContractEvent");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3ca1822-4971-4196-8895-6d51918d887c"),
                            AggregateId = "CTR-20220502-9999",
                            EventData = "{\"ContractNumber\": \"CTR-20220502-9999\",\"CustomerNumber\": \"C13976\",\"ProductNumber\": \"FAC-00011\",\"Amount\": 20000,\"StartDate\": \"2022-05-02T12:40:35.876Z\",\"EndDate\": \"2034-05-02T12:40:35.877Z\",\"EventId\": \"f0074479-4cea-41ff-a669-bdb3649f6e7b\"}",
                            EventType = "ContractRegistered",
                            Timestamp = new DateTime(2022, 10, 10, 12, 56, 49, 301, DateTimeKind.Local).AddTicks(3447),
                            Version = 1L
                        });
                });

            modelBuilder.Entity("ContractManagement.Application.ReadModels.Contract", b =>
                {
                    b.Property<string>("ContractNumber")
                        .HasMaxLength(18)
                        .HasColumnType("nchar(18)")
                        .IsFixedLength();

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CustomerNumber")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .IsFixedLength();

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentPeriod")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ProductNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ContractNumber");

                    b.ToTable("Contract", (string)null);

                    b.HasData(
                        new
                        {
                            ContractNumber = "CTR-20220502-9999",
                            Amount = 20000m,
                            CustomerNumber = "C13976",
                            EndDate = new DateTime(2034, 5, 2, 14, 40, 35, 877, DateTimeKind.Local),
                            PaymentPeriod = "Monthly",
                            ProductNumber = "FAC-00011",
                            StartDate = new DateTime(2022, 5, 2, 14, 40, 35, 876, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("ContractManagement.Application.ReadModels.Customer", b =>
                {
                    b.Property<string>("CustomerNumber")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .IsFixedLength();

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerNumber");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerNumber = "C13976",
                            Address = "Mainstreet 5463",
                            EmailAddress = "jd@example.com",
                            Name = "John Doe"
                        },
                        new
                        {
                            CustomerNumber = "C13977",
                            Address = "First Av. 16743",
                            EmailAddress = "eric.dewitt@example.com",
                            Name = "Eric Dewitt"
                        });
                });

            modelBuilder.Entity("ContractManagement.Application.ReadModels.Product", b =>
                {
                    b.Property<string>("ProductNumber")
                        .HasMaxLength(18)
                        .HasColumnType("nchar(18)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductNumber");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductNumber = "FAC-00011",
                            Description = "Standard long term loan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
